### ISSUE TITLE
Client crash while waiting for transaction

### ISSUE THREAD

**Issue by indyjo** [indyjo/bitwrk#101]
Crash happened on 02:07:51.463317514

<pre>
2014/12/19 02:07:50 [Worker "blender-57138"/Sell #325] Waiting for permission
2014/12/19 02:07:50 [Worker "blender-57138"/Sell #325] Got permission. Price: uBTC 26
2014/12/19 02:07:51 [Worker "blender-57138"/Sell #325] Got bid id: aghzfmJpdHdya3IQCxIDQmlkGICAgJC-waAKDA
2014/12/19 02:07:51 [Worker "blender-57138"/Sell #325] Sell finished
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1 pc=0x4882ed]

goroutine 1991 [running]:
runtime.panic(0x7aa4a0, 0xa267b3)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/indyjo/bitwrk-client.(*Trade).awaitTransaction(0xc208cab540, 0x7f0e87971a18, 0xc2090d2520, 0x0, 0x0)
        /home/bitwrk/bitwrk/src/github.com/indyjo/bitwrk-client/trade.go:167 +0x1fd
github.com/indyjo/bitwrk-client.(*Trade).beginTrade(0xc208cab540, 0x7f0e87971a18, 0xc2090d2520, 0xc2080d4cc0, 0x0, 0x0)
        /home/bitwrk/bitwrk/src/github.com/indyjo/bitwrk-client/trade.go:88 +0x6c6
github.com/indyjo/bitwrk-client.(*SellActivity).doPerformSell(0xc208cab540, 0x7f0e87971a18, 0xc2090d2520, 0xc2080a69c0, 0xc2080d4cc0, 0x0, 0x0)
        /home/bitwrk/bitwrk/src/github.com/indyjo/bitwrk-client/sell.go:76 +0xca
github.com/indyjo/bitwrk-client.(*SellActivity).PerformSell(0xc208cab540, 0x7f0e87971a18, 0xc2090d2520, 0xc2080a69c0, 0xc2080d4cc0, 0x0, 0x0)
        /home/bitwrk/bitwrk/src/github.com/indyjo/bitwrk-client/sell.go:67 +0x140
github.com/indyjo/bitwrk-client.(*WorkerState).executeSell(0xc208107260, 0x7f0e87971a18, 0xc2080a6e80, 0xc208cab540, 0xc2080d4cc0)
        /home/bitwrk/bitwrk/src/github.com/indyjo/bitwrk-client/worker.go:155 +0x1a8
created by github.com/indyjo/bitwrk-client.(*WorkerState).offer
        /home/bitwrk/bitwrk/src/github.com/indyjo/bitwrk-client/worker.go:140 +0x446
</pre>

**Comment by indyjo** [comment]
Happened again on 2015-01-10 at 05:00 UTC

**Comment by indyjo** [comment]
This behavior is caused by Google App Engine suddenly eating "ETag" headers from generated responses, on which the clients rely for caching bids and transactions.

Proposed solution:
 - change internal logic and interfaces to no longer rely on ETag so badly
 - provide workaround for ETag, i.e. X-ETag header
 - get this issue resolved with Google (see https://code.google.com/p/googleappengine/issues/detail?id=11594)
