### ISSUE TITLE
ERROR 5 Blender-Slave.py

### ISSUE THREAD

**Issue by cocco1960** [indyjo/bitwrk#157]
Traceback (most recent call last):
  File "C:\Users\utente\Downloads\bitwrk-0.6.2-src\bitwrk-blender\render_bitwrk\blender-slave.py", line 468, in <module>
    BLENDER_VERSION=get_blender_version()
  File "C:\Users\utente\Downloads\bitwrk-0.6.2-src\bitwrk-blender\render_bitwrk\blender-slave.py", line 430, in get_blender_version
    proc = subprocess.Popen([BLENDER_BIN, '-v'], stdout=subprocess.PIPE)
  File "C:\Users\utente\Downloads\bitwrk-0.6.2-src\bitwrk-blender\render_bitwrk\lib\subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "C:\Users\utente\Downloads\bitwrk-0.6.2-src\bitwrk-blender\render_bitwrk\lib\subprocess.py", line 1112, in _execute_child
    startupinfo)
PermissionError: [WinError 5] Access Denied

When running the script I have already tried running as an admin

**Comment by indyjo** [comment]
If you started the worker via command line, could you post the complete command including arguments? Did you point to the correct Blender.exe? Also, what happens if you double-click that exe?

**Comment by indyjo** [comment]
Closed because of inactivity.
