### ISSUE TITLE
Error when hitting Render

### ISSUE THREAD

**Issue by krz4tw** [indyjo/bitwrk#160]
BitWrk rendering failed with an exception if
 - there was no object selected
 - the current selection was not a normal object, such as a linked object.

Original bug report:

```
Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\render_bitwrk\blendfile.py", line 107, in <module>
    _repath()
  File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\render_bitwrk\blendfile.py", line 50, in _repath
    bpy.ops.object.mode_set(mode='OBJECT')
  File "D:\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect
Error: Exception while rendering: Traceback (most recent call last):
  File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\render_bitwrk\render.py", line 158, in render
    self._doRender(scene, tmpdir)
  File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\render_bitwrk\render.py", line 171, in _doRender
    process_file(filename)
  File "C:\Users\xxxxxxxx\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\render_bitwrk\blendfile.py", line 41, in process_file
    raise RuntimeError("Error processing file '{}': Calling blender returned code {}".format(filepath, ret))
RuntimeError: Error processing file 'C:\Users\xxxxxxxx\AppData\Local\Temp\tmpdhs3770s
\mainfile.blend': Calling blender returned code 4294967295

```
Installed Pugin as shown, selected renderer, selected client file, started client, hit render.
No colored tiles, just this error.

**Comment by indyjo** [comment]
How to reproduce:

- Start with default cube scene
- Delete default cube
- Render without any object selected
